name: Deploy website to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Download website ZIP
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo "${{ github.repository }}" --pattern "build.zip" --dir .

      - name: Unpack website
        run: |
          mkdir unpacked
          unzip build.zip -d unpacked || [ $? -eq 1 ]

          if [ -f "unpacked/build/index.html" ]; then
            mv unpacked/build site
          else
            mv unpacked site
          fi

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
